# Generated by Django 5.2.1 on 2025-06-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shift_projecttimeentry_tasktimeentry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_timer_running',
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('high', 'Hoch'), ('medium', 'Mittel'), ('low', 'Niedrig')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('init', 'Initiated'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='init', max_length=20),
        ),
    ]
