# Generated by Django 5.2.1 on 2025-05-23 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_invited_users_alter_project_user_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_timer_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='today_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='project',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
