# Generated by Django 5.2.1 on 2025-06-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttimeentry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
