# Generated by Django 5.2.1 on 2025-06-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_projecttimeentry_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
