# Generated by Django 5.2.1 on 2025-05-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_description_task_due_date_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.task'),
            preserve_default=False,
        ),
    ]
