# Generated by Django 5.2.1 on 2025-05-27 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_timeentry_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
